### ISSUE TITLE
El estilo del título no coincide con el estilo del sitio.

### ISSUE THREAD

**Issue by salvadorc94** [salvadorc94/AMSSCovid19Map#2]
Sugiero cambiar el estilo:
![image](https://user-images.githubusercontent.com/29514777/85467285-41008200-b568-11ea-84b9-98e1fdd57590.png)

**Comment by JorgeAzzuFranco** [comment]
El titulo del geoportal ha sido cambiado:

![imagen](https://user-images.githubusercontent.com/37319677/86523068-ec8cba80-be23-11ea-979c-8f0d93d7a123.png)
