### ISSUE TITLE
Botón de centrar mapa desalineado

### ISSUE THREAD

**Issue by JorgeAzzuFranco** [salvadorc94/AMSSCovid19Map#4]
El botón para centrar el mapa no está en el centro.
![imagen](https://user-images.githubusercontent.com/37319677/86524309-2bc40700-be36-11ea-8883-62f3185e4d2c.png)

**Comment by MarleneBarahona** [comment]
![image](https://user-images.githubusercontent.com/37312777/86524536-fc62c980-be38-11ea-8d2d-e88e21ddcf19.png)

**Comment by MarleneBarahona** [comment]
El botón ha sido centrado. Además, se le ha cambiado el estilo para que esté acorde al tema del sitio.
