### ISSUE TITLE
Bug con botón Ver en Mapa

### ISSUE THREAD

**Issue by salvadorc94** [salvadorc94/AMSSCovid19Map#8]
El botón funciona, hace zoom en el mapa, pero si se está abajo en la tabla y se le da al botón, la página no sube automáticamente para mostrar el cambio. El usuario debe subir manualmente para ver el cambio en el mapa.

**Comment by MarleneBarahona** [comment]
Se ha implementado la función de subir en la pagina al darle al botón en la tabla correspondiente a ver cada municipio, para así ver el mapa actualizado.
